# -*- coding: utf-8 -*-
from PyQt5.QtWidgets import QTableView
from EventControll.FunctionControl import *
from Window.Info_Window import  *

def Ui_StartWindow():
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

class Ui_MainWindow(object):


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1283, 808)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 1041, 361))
        self.groupBox.setObjectName("groupBox")
        self.tv_company = QtWidgets.QLineEdit(self.groupBox)
        self.tv_company.setGeometry(QtCore.QRect(90, 30, 901, 20))
        self.tv_company.setObjectName("tv_company")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 71, 21))
        self.label.setObjectName("label")
        self.tv_establish = QtWidgets.QLineEdit(self.groupBox)
        self.tv_establish.setGeometry(QtCore.QRect(90, 190, 113, 20))
        self.tv_establish.setObjectName("tv_establish")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 190, 71, 21))
        self.label_2.setObjectName("label_2")
        self.tv_companySales = QtWidgets.QLineEdit(self.groupBox)
        self.tv_companySales.setGeometry(QtCore.QRect(90, 230, 113, 20))
        self.tv_companySales.setObjectName("tv_companySales")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 230, 71, 21))
        self.label_3.setObjectName("label_3")
        self.tv_sales = QtWidgets.QLineEdit(self.groupBox)
        self.tv_sales.setGeometry(QtCore.QRect(500, 190, 113, 20))
        self.tv_sales.setObjectName("tv_sales")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(430, 190, 71, 21))
        self.label_4.setObjectName("label_4")
        self.tv_location = QtWidgets.QLineEdit(self.groupBox)
        self.tv_location.setGeometry(QtCore.QRect(300, 190, 111, 20))
        self.tv_location.setObjectName("tv_location")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(230, 190, 71, 21))
        self.label_5.setObjectName("label_5")
        self.tv_people = QtWidgets.QLineEdit(self.groupBox)
        self.tv_people.setGeometry(QtCore.QRect(300, 230, 111, 20))
        self.tv_people.setObjectName("tv_people")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(230, 230, 71, 21))
        self.label_6.setObjectName("label_6")
        self.tv_job = QtWidgets.QLineEdit(self.groupBox)
        self.tv_job.setGeometry(QtCore.QRect(500, 230, 113, 20))
        self.tv_job.setObjectName("tv_job")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(430, 230, 71, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 70, 71, 21))
        self.label_8.setObjectName("label_8")
        self.tv_qualification = QtWidgets.QLineEdit(self.groupBox)
        self.tv_qualification.setGeometry(QtCore.QRect(90, 70, 901, 20))
        self.tv_qualification.setObjectName("tv_qualification")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(10, 110, 71, 21))
        self.label_9.setObjectName("label_9")
        self.tv_preferential = QtWidgets.QLineEdit(self.groupBox)
        self.tv_preferential.setGeometry(QtCore.QRect(90, 110, 901, 20))
        self.tv_preferential.setObjectName("tv_preferential")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(10, 150, 71, 21))
        self.label_11.setObjectName("label_11")
        self.tv_type = QtWidgets.QLineEdit(self.groupBox)
        self.tv_type.setGeometry(QtCore.QRect(90, 150, 901, 20))
        self.tv_type.setObjectName("tv_type")
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(630, 190, 71, 21))
        self.label_14.setObjectName("label_14")
        self.tv_welfare = QtWidgets.QLineEdit(self.groupBox)
        self.tv_welfare.setGeometry(QtCore.QRect(700, 230, 291, 20))
        self.tv_welfare.setObjectName("tv_welfare")
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(630, 230, 71, 21))
        self.label_15.setObjectName("label_15")
        self.tv_process = QtWidgets.QLineEdit(self.groupBox)
        self.tv_process.setGeometry(QtCore.QRect(700, 190, 291, 20))
        self.tv_process.setText("")
        self.tv_process.setObjectName("tv_process")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 270, 791, 80))
        self.groupBox_4.setObjectName("groupBox_4")
        self.tv_volunteer = QtWidgets.QLineEdit(self.groupBox_4)
        self.tv_volunteer.setGeometry(QtCore.QRect(680, 50, 71, 20))
        self.tv_volunteer.setObjectName("tv_volunteer")
        self.label_19 = QtWidgets.QLabel(self.groupBox_4)
        self.label_19.setGeometry(QtCore.QRect(310, 20, 71, 21))
        self.label_19.setObjectName("label_19")
        self.label_26 = QtWidgets.QLabel(self.groupBox_4)
        self.label_26.setGeometry(QtCore.QRect(10, 50, 61, 21))
        self.label_26.setObjectName("label_26")
        self.label_25 = QtWidgets.QLabel(self.groupBox_4)
        self.label_25.setGeometry(QtCore.QRect(480, 50, 41, 21))
        self.label_25.setObjectName("label_25")
        self.tv_toeicSpeacking = QtWidgets.QLineEdit(self.groupBox_4)
        self.tv_toeicSpeacking.setGeometry(QtCore.QRect(390, 20, 71, 20))
        self.tv_toeicSpeacking.setObjectName("tv_toeicSpeacking")
        self.tv_toeic = QtWidgets.QLineEdit(self.groupBox_4)
        self.tv_toeic.setGeometry(QtCore.QRect(220, 20, 61, 20))
        self.tv_toeic.setObjectName("tv_toeic")
        self.label_20 = QtWidgets.QLabel(self.groupBox_4)
        self.label_20.setGeometry(QtCore.QRect(480, 20, 41, 21))
        self.label_20.setObjectName("label_20")
        self.tv_grade = QtWidgets.QLineEdit(self.groupBox_4)
        self.tv_grade.setGeometry(QtCore.QRect(70, 20, 61, 20))
        self.tv_grade.setObjectName("tv_grade")
        self.label_17 = QtWidgets.QLabel(self.groupBox_4)
        self.label_17.setGeometry(QtCore.QRect(10, 20, 61, 21))
        self.label_17.setObjectName("label_17")
        self.tv_certificate = QtWidgets.QLineEdit(self.groupBox_4)
        self.tv_certificate.setGeometry(QtCore.QRect(70, 50, 61, 20))
        self.tv_certificate.setObjectName("tv_certificate")
        self.tv_opic = QtWidgets.QLineEdit(self.groupBox_4)
        self.tv_opic.setGeometry(QtCore.QRect(530, 20, 71, 20))
        self.tv_opic.setObjectName("tv_opic")
        self.tv_award = QtWidgets.QLineEdit(self.groupBox_4)
        self.tv_award.setGeometry(QtCore.QRect(390, 50, 71, 20))
        self.tv_award.setObjectName("tv_award")
        self.tv_experience = QtWidgets.QLineEdit(self.groupBox_4)
        self.tv_experience.setGeometry(QtCore.QRect(220, 50, 61, 20))
        self.tv_experience.setObjectName("tv_experience")
        self.label_23 = QtWidgets.QLabel(self.groupBox_4)
        self.label_23.setGeometry(QtCore.QRect(620, 50, 61, 21))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.groupBox_4)
        self.label_24.setGeometry(QtCore.QRect(310, 50, 71, 21))
        self.label_24.setObjectName("label_24")
        self.tv_intern = QtWidgets.QLineEdit(self.groupBox_4)
        self.tv_intern.setGeometry(QtCore.QRect(530, 50, 71, 20))
        self.tv_intern.setObjectName("tv_intern")
        self.label_18 = QtWidgets.QLabel(self.groupBox_4)
        self.label_18.setGeometry(QtCore.QRect(160, 20, 61, 21))
        self.label_18.setObjectName("label_18")
        self.label_22 = QtWidgets.QLabel(self.groupBox_4)
        self.label_22.setGeometry(QtCore.QRect(160, 50, 61, 21))
        self.label_22.setObjectName("label_22")
        self.tv_other = QtWidgets.QLineEdit(self.groupBox_4)
        self.tv_other.setGeometry(QtCore.QRect(680, 20, 71, 20))
        self.tv_other.setObjectName("tv_other")
        self.label_21 = QtWidgets.QLabel(self.groupBox_4)
        self.label_21.setGeometry(QtCore.QRect(620, 20, 61, 21))
        self.label_21.setObjectName("label_21")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 400, 1241, 361))
        self.groupBox_2.setObjectName("groupBox_2")



        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_2)
        self.tableWidget.setGeometry(QtCore.QRect(10, 20, 1211, 321))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        self.tableWidget.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)
        self.tableWidget.setSelectionBehavior(QTableView.SelectRows)
        self.tableWidget.setColumnCount(11)
        self.tableWidget.setColumnWidth(0, 150)
        self.tableWidget.setColumnWidth(2, 100)
        self.tableWidget.setColumnWidth(3, 150)
        self.tableWidget.setHorizontalHeaderLabels(
            ['회사 이름', '평균 연봉', '직종', '지역', '우대 사항', '자격 요건', '설립일', '종업원', '매출액', '인재상', '복지종류'])

        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(1090, 10, 171, 361))
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton.setGeometry(QtCore.QRect(20, 30, 131, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 80, 131, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 130, 131, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 180, 131, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1283, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.buttonEventInit()
        self.retranslateUi(MainWindow)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def buttonEventInit(self):
        self.ButtonControl = FucntionControl(self)

        self.pushButton.clicked.connect(self.ButtonControl.btn_insert)

        self.pushButton_2.clicked.connect(self.ButtonControl.btn_delete)
        self.pushButton_3.clicked.connect(self.ButtonControl.btn_update)
        self.pushButton_4.clicked.connect(self.ButtonControl.btn_refresh)

        self.tableWidget.doubleClicked.connect(self.ButtonControl.btn_openInfo)
        self.tableWidget.clicked.connect(self.ButtonControl.btn_listviewItemClick)
        self.tableWidget.selectionModel().currentIndex().row()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "정보창"))
        self.label.setText(_translate("MainWindow", "회사 이름 : "))
        self.label_2.setText(_translate("MainWindow", "설  립  일 :"))
        self.label_3.setText(_translate("MainWindow", "매  출  액 :"))
        self.label_4.setText(_translate("MainWindow", "평균 연봉 :"))
        self.label_5.setText(_translate("MainWindow", "주      소:"))
        self.label_6.setText(_translate("MainWindow", "종  업  원 :"))
        self.label_7.setText(_translate("MainWindow", "직      종  :"))
        self.label_8.setText(_translate("MainWindow", "자격 요건 :"))
        self.label_9.setText(_translate("MainWindow", "우대 사항 :"))
        self.label_11.setText(_translate("MainWindow", "인 재 상 :"))
        self.label_14.setText(_translate("MainWindow", "채용 절차 :"))
        self.label_15.setText(_translate("MainWindow", "복지 종류 :"))
        self.groupBox_4.setTitle(_translate("MainWindow", "합격 스펙"))
        self.label_19.setText(_translate("MainWindow", "토익스피킹 :"))
        self.label_26.setText(_translate("MainWindow", "자 격 증 :"))
        self.label_25.setText(_translate("MainWindow", "인 턴 :"))
        self.label_20.setText(_translate("MainWindow", "OPIC :"))
        self.label_17.setText(_translate("MainWindow", "학    점  :"))
        self.label_23.setText(_translate("MainWindow", "봉사횟수 :"))
        self.label_24.setText(_translate("MainWindow", "수상  내역  :"))
        self.label_18.setText(_translate("MainWindow", "토     익  :"))
        self.label_22.setText(_translate("MainWindow", "해외경험 :"))
        self.label_21.setText(_translate("MainWindow", "외 국 어 :"))
        self.groupBox_2.setTitle(_translate("MainWindow", "회사 정보"))
        self.groupBox_3.setTitle(_translate("MainWindow", "기능"))
        self.pushButton.setText(_translate("MainWindow", "입력"))
        self.pushButton_2.setText(_translate("MainWindow", "삭제"))
        self.pushButton_3.setText(_translate("MainWindow", "수정"))
        self.pushButton_4.setText(_translate("MainWindow", "새로 고침"))


